```{r solution, echo = FALSE, results = "hide",cache=TRUE}
library(GetQuandlData)

id_series <- c(COFFEE = 'CEPEA/COFFEE_A')

# set api key (make sure you got your own!)
#my_api_key <- readLines('~/Dropbox/98-pass_and_bash/.quandl_api.txt')

first_date <- '2010-01-01'
last_date <- '2020-12-31'

#df_coffee <- get_Quandl_series(id_in = id_series, 
 #                              first_date = first_date,
  #                             last_date = last_date,
   #                            api_key = my_api_key,
    #                           do_cache = TRUE)

# find most recent
#idx <- which.max(df_coffee$ref_date)
#my_sol <- as.numeric(df_coffee$`Cash Price US$`[idx])
```

```{r datageneration, echo = FALSE, results = "hide"}
#my_answer <- afedR::make_random_answers(my_sol)

#afedR::check_answers(my_answers)
```

Question
========

If you have not already done so, create a profile on the [Quandl website](https://www.quandl.com/)^[https://www.quandl.com/] and download the arabica coffee price data in the CEPEA database (Center for Advanced Studies in Applied Economics) ) between `r first_date` and `r last_date`. What is the value of the most recent price?


Solution
================

```{r solution, eval=FALSE}
```


Meta-information
================
extype: string
exsolution: `r NA`
exname: "quandl"
exshuffle: TRUE

